version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20.1-browsers

    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      
      - run:
          name: "Installing Node Dependencies"
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run:
          name: "Testing Project"
          command: npm test
